### ISSUE TITLE
crash al poner cheque en cartera

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_check_ar#3]
```python
Traceback (most recent call last):
  File "/trytond/wsgi.py", line 47, in dispatch_request
    return endpoint(request, **request.view_args)
  File "/trytond/protocols/dispatcher.py", line 41, in rpc
    request, database_name, *request.rpc_params)
  File "/trytond/wsgi.py", line 39, in auth_required
    return wrapped(*args, **kwargs)
  File "/trytond/protocols/wrappers.py", line 106, in wrapper
    return func(request, pool, *args, **kwargs)
  File "/trytond/protocols/dispatcher.py", line 163, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/trytond/wizard/wizard.py", line 287, in execute
    return wizard._execute(state_name)
  File "/trytond/wizard/wizard.py", line 318, in _execute
    result = self._execute(transition())
  File "/trytond/modules/account_check_ar/account_check_ar.py", line 308, in transition_held
    'account': self.start.journal.third_check_account.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by lukio** [comment]
Esto sucede porque no esta seteado el campo third check account en el diario que se configuro.
